version: "3"

services:

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    command: -c shared_buffers=256MB -c max_connections=200
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - services_default
    restart: always



  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    env_file:
      - .env
    logging:
      driver: none
    networks:
      - services_default

  mongo_nef:
    image: mongo:4.4.10
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    networks:
      - services_default

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo_nef:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "${MONGO_EXPRESS_ENABLE_ADMIN}"
    networks:
      - services_default

  
  backend:
    image: 'tgogos/nef_emulatoer:v1.6.1_e35e6e'
    command: /start-reload.sh
    ports:
      - "${SERVER_PORT}:80"
    restart: always
    env_file:
      - .env
    environment:
      # - SERVER_NAME=${DOMAIN?Variable not set}
      # - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        INSTALL_JUPYTER: ${INSTALL_JUPYTER-true}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services_default


networks:
    services_default:
      # external: ${EXTERNAL_NET}


volumes:
  app-db-data:
  pgadmin-data:
  app-mongo-db-data:

